In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import tree

In [5]:
df=pd.read_csv('winequality-red.csv',sep=';')

In [6]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [8]:
y = df.quality
X = df.drop('quality', axis=1)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)

In [10]:
X_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1264            8.5              0.37         0.32             1.8      0.066   
1215            8.8              0.27         0.46             2.1      0.095   
951             8.3              0.28         0.48             2.1      0.093   
1125            8.8              0.24         0.35             1.7      0.055   
551             9.4              0.43         0.24             2.8      0.092   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1264                 26.0                  51.0  0.99456  3.38       0.72   
1215                 20.0                  29.0  0.99488  3.26       0.56   
951                   6.0                  12.0  0.99408  3.26       0.62   
1125                 13.0                  27.0  0.99394  3.14       0.59   
551                  14.0                  45.0  0.99800  3.19       0.73   

      alcohol  
1264     11.8  
1215     11.3  
951      12.4  
1125     11.3  
551      10.0

In [12]:
X_train_scaled = preprocessing.scale(X_train)
X_train_scaled

array([[ 0.06638319, -0.87988026,  0.2223387 , ...,  0.48297375,
         0.35601827,  1.32861276],
       [ 0.23619138, -1.43296763,  0.93632664, ..., -0.30443661,
        -0.58187538,  0.85176471],
       [-0.04682227, -1.37765889,  1.03832492, ..., -0.30443661,
        -0.23016526,  1.90083042],
       ...,
       [-0.04682227,  0.00505952, -1.40963374, ..., -0.37005414,
        -0.11292856, -0.38804023],
       [ 1.19843781, -0.10555796,  1.85431114, ..., -1.41993463,
         0.00430815,  1.32861276],
       [-0.04682227,  0.66876435, -0.89964235, ..., -0.10758402,
        -0.64049374, -0.86488828]])

In [13]:
dtree=tree.DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [14]:
confidence = dtree.score(X_test, y_test)
print("\nThe confidence score:\n")
print(confidence)


The confidence score:

0.60625


In [16]:
y_pred = dtree.predict(X_test)

In [20]:
from sklearn.metrics import classification_report,confusion_matrix

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.18      0.22      0.20         9
           5       0.63      0.67      0.65       123
           6       0.66      0.63      0.64       140
           7       0.54      0.50      0.52        42
           8       0.25      0.25      0.25         4

    accuracy                           0.61       320
   macro avg       0.38      0.38      0.38       320
weighted avg       0.61      0.61      0.61       320



In [22]:
print(confusion_matrix(y_test,y_pred))

[[ 0  0  1  1  0  0]
 [ 2  2  3  2  0  0]
 [ 0  6 82 31  4  0]
 [ 0  0 38 88 13  1]
 [ 0  3  7  9 21  2]
 [ 0  0  0  2  1  1]]


In [19]:
#converting the numpy array to list
x=np.array(y_pred).tolist()

#printing first 5 predictions
print("\nThe prediction:\n")
for i in range(0,5):
    print(x[i])
    
#printing first five expectations
print("\nThe expectation:\n")
y_test.head()


The prediction:

6
6
6
5
6

The expectation:



1271    6
537     6
1390    6
1154    6
1116    6
Name: quality, dtype: int64